services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - "5000:5000"
    volumes:
      - ./log_data/:/app/log_data/
      - ./analysis_results/:/app/analysis_results
      - .:/app
    environment:
      DB_URL: "postgresql://postgres:postgres@db:5432/postgres"
      LOG_DATA_DIRECTORY: "./log_data/"
      RESULTS_DIRECTORY: "./analysis_results/"
      CELERY_BROKER_URL: "redis://redis:6379/0"
      FLASK_DEBUG: 1
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
  celery:
    build:
      context: .
      dockerfile: Dockerfile-dev
    command: celery -A server.make_celery worker --concurrency=4 --loglevel=info
    volumes:
      - .:/app
    environment:
      DB_URL: "postgresql://postgres:postgres@db:5432/postgres"
      LOG_DATA_DIRECTORY: "./log_data/"
      RESULTS_DIRECTORY: "./analysis_results/"
      CELERY_BROKER_URL: "redis://redis:6379/0"
    depends_on:
      - redis
      - db
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      TZ: Europe/Helsinki
      PGTZ: Europe/Helsinki
    volumes:
      - db_data:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

volumes:
  db_data:
