"""Add normalization option to line level analysis

Revision ID: 1fce494a5a86
Revises: a9fe74ac20ca
Create Date: 2025-08-27 13:25:04.838544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fce494a5a86'
down_revision = 'a9fe74ac20ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('line_level_normalization', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_column('line_level_normalization')

    # ### end Alembic commands ###
