"""Add name to analysis model

Revision ID: 386df161b1ab
Revises: 54115e331d02
Create Date: 2025-08-07 14:08:25.652710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '386df161b1ab'
down_revision = '54115e331d02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
