"""Add name to analysis model

Revision ID: 3bf3bed0f5b4
Revises: 54115e331d02
Create Date: 2025-08-07 12:26:46.612008

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3bf3bed0f5b4"
down_revision = "54115e331d02"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("analyses") as batch_op:
        batch_op.add_column(sa.Column("name", sa.String(), nullable=True))

    op.execute("UPDATE analyses SET name = analysis_sub_type WHERE name IS NULL")

    with op.batch_alter_table("analyses") as batch_op:
        batch_op.alter_column("name", nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("analyses", schema=None) as batch_op:
        batch_op.drop_column("name")

    # ### end Alembic commands ###
