"""Initial migration

Revision ID: 54115e331d02
Revises: 
Create Date: 2025-08-07 10:48:52.687128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54115e331d02'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('results_path', sa.String(), nullable=False),
    sa.Column('analysis_type', sa.String(), nullable=False),
    sa.Column('analysis_sub_type', sa.String(), nullable=False),
    sa.Column('analysis_level', sa.String(), nullable=False),
    sa.Column('mask_type', sa.String(), nullable=True),
    sa.Column('vectorizer', sa.String(), nullable=True),
    sa.Column('enhancement', sa.String(), nullable=True),
    sa.Column('models', sa.String(), nullable=True),
    sa.Column('directory_path', sa.String(), nullable=True),
    sa.Column('train_data_path', sa.String(), nullable=True),
    sa.Column('test_data_path', sa.String(), nullable=True),
    sa.Column('target', sa.String(), nullable=True),
    sa.Column('item_list_col', sa.String(), nullable=True),
    sa.Column('match_filenames', sa.Boolean(), nullable=True),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_filenames', sa.Boolean(), nullable=True),
    sa.Column('color_by_directory', sa.Boolean(), nullable=True),
    sa.Column('line_level_display_mode', sa.String(), nullable=True),
    sa.Column('manual_filename_input', sa.Boolean(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings')
    op.drop_table('analyses')
    op.drop_table('projects')
    # ### end Alembic commands ###
